name: benchmarks
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - numpy=1.21
  - pip:
    - qibo
    - qibotf
    - qibojit
    - qiskit
    - qiskit-aer-gpu
    - qulacs
    - cirq
    - qsimcirq
    - qcgpu
    - projectq

